#regular:
#  enabled: true #メッセージの送信するか
#  random: false #ランダムに送信するか
#  time: '14:55' #メッセージを送信する時間
#  expiry: -1　 #ここは変更しないように
#  messages:
#    - 'ここにメッセージを書く'
#    - '次に'

#注意　インデントを絶対に合わせる

settings:
  enabled: true
  min-players: 0
  log-to-console: false
message-lists:
  regular:
    enabled: true
    random: false
    time: '14:55'
    expiry: -1
    messages:
      - "&cここにメッセージを書く \n改行もできるよん"
  json:
    enabled: true
    random: false
    time: '2:55'
    expiry: -1
    messages:
      - |- #これが仕切り
        {
          "color":"gold",
          "extra":[
            {
              "bold":true,
              "color":"aqua",
              "text":"world"
            },
            {
              "color":"red",
              "text":"!"
            },
            {
              "clickEvent":{
                "action":"open_url",
                "value":"https://hatosaba.f5.si/"
              },
              "text":"グーグルを開く"
            },
            {
              "clickEvent":{
                "action":"suggest_command",
                "value":"/say aiueo"
              },
              "text":"コンプリートみたいなやつ"
            },
            {
              "clickEvent":{
                "action":"run_command",
                "value":"/gamemode c"
              },
              "text":"コマンドを実行"
            },
            {
              "clickEvent":{
                "action":"copy_to_clipboard",
                "value":"できないみたい"
              },
              "text":"クリックボードにコピー"
            },
            {
              "hoverEvent":{
                "action":"show_text",
                "contents":{
                  "color":"red",
                  "text":"見ないで.."
                }
              },
              "text":"かざして"
            }
          ],
          "text":"Hello "
        }
